media_album:
    resource: "@MediaBundle/Resources/config/routing/album.yml"
    prefix:   /album

media_homepage:
    path:     /
    defaults: { _controller: MediaBundle:Default:index }

media_listealbums:
    path:     /
    defaults: { _controller: MediaBundle:Default: }

